print("hello world")
print("hello world again form the rekya ko papa hehe hasdle a remote repo")
print("hello world againgafsdfsdfsf form the remote repo")
print("hello world again from new user")
print("why this colabery")
print("Mula sandesh")
print("Hamile Sikkyau ")
print("Katta khanxas ")
print("Class siddiya paxi sikkiyanau vynee ")
print("chutya haru")